### ISSUE TITLE
Missing repositories for waltid-ssi-kit

### ISSUE THREAD

**Issue by tdiesler** [walt-id/waltid-wallet-docs#1]
```
The following artifacts could not be resolved: 
info.weboftrust:ld-signatures-java:jar:0.5-SNAPSHOT, 
decentralized-identity:jsonld-common-java:jar:0.2.0, com.github.multiformats:java-multibase:jar:v1.1.0: 
Could not find artifact info.weboftrust:ld-signatures-java:jar:0.5-SNAPSHOT in mavenCentral (https://repo1.maven.org/maven2/) -> [Help 1]
```

**Comment by tdiesler** [comment]
You'll also need ...

```
        <repository>
            <id>danubetech-maven-public</id>
            <url>https://repo.danubetech.com/repository/maven-public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
```

**Comment by tdiesler** [comment]
PR: https://github.com/walt-id/waltid-wallet-docs/pull/2

**Comment by cpatsonakis** [comment]
Hello!

Thank you for your interest in our stack first of all. Next, as stated in the repository's README:
Please be informed that, beginning from December 2023, the Wallet Kit will no longer receive new features. Furthermore, the Wallet Kit is planned for discontinuation by the end of Q3 2024.
However, all functionalities offered by the Wallet Kit are now integrated into our new libraries, APIs, and apps in the walt.id [identity repo](https://github.com/walt-id/waltid-identity). Giving you more modularity, flexibility and ease-of-use to build end-to-end digital identity and wallet solutions.

For more up-to-date developments, please refer to our community stack repo as the development of this repository has been discontinued.

Thanks again and hope to hear more from you soon!
